version: '2'
services:
  php:
    build: ./images/php
    links:
      - mysql
      - postgresql
    container_name: php-common
    volumes:
      - ./www:/var/www
  nginx:
    container_name: nginx-common
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d:ro
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  mysql:
    image: mysql:8
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: qwerty
  postgresql:
    image: postgres:9.6.3
    ports:
      - "5432:5432"
    environment:
      - DB_PASS=qwerty
    volumes:
      - ./postgresql:/var/lib/postgresql
